font_family      Maple Mono NF
font_size        18
font_features    MapleMono-NF-Regular +cv01 +liga +calt
modify_font      cell_height 110%

cursor_shape           block
cursor_blink_interval  0.5
cursor_trail                 3
cursor_trail_decay           0.1 0.4
cursor_trail_start_threshold 2

background        #000000
foreground        #ffffff
cursor            #fefefe
cursor_text_color #000000
selection_background #222222
selection_foreground #cccccc

color0  #000000
color1  #f07178
color2  #c3e88d
color3  #ffcb6b
color4  #82aaff
color5  #c792ea
color6  #89ddff
color7  #cccccc
color8  #404040
color9  #f6a9ae
color10 #dbf1ba
color11 #ffdfa6
color12 #b4ccff
color13 #ddbdf2
color14 #b8eaff
color15 #ffffff

placement_strategy      center
confirm_os_window_close 0
background_opacity      0.6
background_blur         25

mouse_hide_wait         3.0
wheel_scroll_multiplier 3.0
focus_follows_mouse     no

shell_integration       no-cursor no-title

scrollback_lines        100000

clipboard_control       write-clipboard write-primary read-clipboard read-primary
paste_actions           quote-urls-at-prompt,confirm-if-large
