github.com:
    users:
        guru-krithick:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: guru-krithick
